name: Dev Branch CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.12.3
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.3'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Validate JSON files
      run: |
        # put commands in to validate my JSON files

        jq empty data/json_data/enemies.json
        jq empty data/json_data/items.json
        jq empty data/json_data/npcs.json
        jq empty data/json_data/player.json
        jq empty data/json_data/quests.json
        jq empty data/json_data/world.json

    - name: Run tests
      run: |
        # put commands in to run tests

        python -m unittest discover -s tests
